name: Admin - Frontend App - Build and Deploy Docker Image

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'code/backend/Admin.py'
      - 'code/backend/pages/**'

  pull_request:
    branches: [main]
    types:
        - opened
        - ready_for_review
        - reopened
        - synchronize

    paths:
      - 'code/backend/Admin.py'
      - 'code/backend/pages/**'

permissions:
  contents: read
  id-token: write


jobs:
  build-push-docker-image:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/reusable-build-push-docker-image.yml
    with:
      dockerfile: "docker/Admin.Dockerfile"
      image_name: "admin-frontend-app"
      tag_name: ${{ github.run_number }}
    secrets:
      inherit


  # This job runs only when the change is pushed to main branch
  copy-acr-image:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable-copy-docker-image.yml
    with:
      image_name: "admin-frontend-app"
      source_environment: "dev"
      destination_environment: "prod"
    secrets:
      inherit

  deploy-app:
    needs: [build-push-docker-image, copy-acr-image]
    if: needs.build-push-docker-image.result == 'success' || needs.copy-acr-image.result == 'success'
    uses: ./.github/workflows/reusable-deploy-docker-image.yml
    with:
      image_name: "admin-frontend-app"
      deploy_command: "app-service"
      service_name: "admin-frontend-app"
      tag_name: ${{ github.run_number }}
    secrets:
      inherit
